import Head from "next/head";
import Navigation from "../navigation/navigation";
import Logo from "../logo/logo";
import Footer from "../footer/footer";

export default function Layout({ children }) {
  return (
    <div className="flex flex-col min-h-screen">
      <Head>
        <title>Next Shop System</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="flex p-2.5 justify-between">
        <Logo></Logo>
        <Navigation></Navigation>
      </header>
      <main className="p-2.5 flex-grow">{children}</main>
      <Footer></Footer>
    </div>
  );
}
